services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/LMS.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=LmsDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - Jwt__Key=super-secret-dev-key-change-in-production-min-32-chars!!
      - Jwt__Issuer=LmsApi
      - Jwt__Audience=LmsClient
    depends_on:
      - db

volumes:
  sqldata:
